# .readthedocs.yaml
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

sphinx:
  configuration: V01/source/conf.py
  fail_on_warning: false

formats:
  - pdf
  - htmlzip

python:
   install:

     - requirements: requirements.txt
